name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@968872560f81e7bdde9272853e65f2507c0eca7c # v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
